CHECKLIST_ITEMS = [
    {"sr_no": 1, "parameter": "The NISM Certificates (F&O, Currency, Commodity) of all active terminals", "remark": "na"},
    {"sr_no": 2, "parameter": "Image of display of Notice Board", "remark": "yes"},
    {"sr_no": 3, "parameter": "Glow Sign Board", "remark": "no"},
    {"sr_no": 4, "parameter": "Image of display of Investor Charter (Investor Charter Stock Brokers)", "remark": "yes"},
    {"sr_no": 5, "parameter": "Image of display of Investor Charter (DEPOSITORY PARTICIPANT)", "remark": "yes"},
    {"sr_no": 6, "parameter": "Combined AP declaration", "remark": "yes"},
    {"sr_no": 7, "parameter": "Image of display of AP registration Certificate (NSE, BSE, MCX, NCDEX) as per applicability", "remark": "yes"},
    {"sr_no": 8, "parameter": "Image of display of SEBI registration Certificate of broker", "remark": "yes"},
    {"sr_no": 9, "parameter": "Bank Statement for past 01 Year (For Bank Accounts mapped with MOFSL)", "remark": "yes"},
    {"sr_no": 10, "parameter": "Visitor Registers maintained at BA Office", "remark": "yes"},
    {"sr_no": 11, "parameter": "Compliant / Investor Grievance Register maintained at BA Office", "remark": "yes"},
    {"sr_no": 12, "parameter": "Inward / Outward Register maintained at BA Office", "remark": "no"},
    {"sr_no": 13, "parameter": "Order instruction register or call recording samples (latest) whichever maintained at BA Office", "remark": "yes"},
    {"sr_no": 14, "parameter": "Trade Detail obtained for the same day", "remark": "yes"},
    {"sr_no": 15, "parameter": "Terminal ID no. verification photo", "remark": "yes"},
    {"sr_no": 16, "parameter": "Approved User Photo ID proof (aadhar/pan/driving licence / voter id)", "remark": "yes"},
    {"sr_no": 17, "parameter": "Grivance Board", "remark": "yes"},
    {"sr_no": 18, "parameter": "Auditor Selfie", "remark": "yes"},
    {"sr_no": 19, "parameter": "AP on same address as provided", "remark": "yes"},
    {"sr_no": 20, "parameter": "No illegal/dabba/cash trading", "remark": "yes"},
    {"sr_no": 21, "parameter": "No Advertisement", "remark": "yes"},
    {"sr_no": 22, "parameter": "Bank Account Verification", "remark": ""},
    {"sr_no": 23, "parameter": "There is no change/shifting of location of AP/Branch (If Yes then All clients mapped to the AP/Branch are notified at least thirty days before the change.)", "remark": "no"},
    {"sr_no": 24, "parameter": "No changes in the AP/Branch contact details, such as address, email, or mobile number, ( If Yes, then must be correctly reported )", "remark": "no"},
    {"sr_no": 25, "parameter": "AP name not implying advisory services or providing investment services to clients (if yes check SEBI registration certificates)", "remark": "no"},
    {"sr_no": 26, "parameter": "Any other observations or irregularities", "remark": "no"}
]
