
CHECKLIST_ITEMS = [
    {"sr_no": 1, "parameter": "NISM Certificates (F&O, Currency, Commodity) of all active terminals", "remark": "na"},
    {"sr_no": 2, "parameter": "Image of display of Notice Board", "remark": "yes"},
    {"sr_no": 3, "parameter": "Glow Sign Board", "remark": "yes"},
    {"sr_no": 4, "parameter": "Image of display of Investor Charter (Investor Charter Stock Brokers)", "remark": "yes"},
    {"sr_no": 5, "parameter": "Image of display of Investor Charter (DEPOSITORY PARTICIPANT)", "remark": "yes"},
    {"sr_no": 6, "parameter": "Combined AP declaration (Refer Formats section for declaration)", "remark": "yes"},
    {"sr_no": 7, "parameter": "Image of display of AP registration Certificate (NSE, BSE, MCX, NCDEX) as per applicability", "remark": "yes"},
    {"sr_no": 8, "parameter": "Image of display of Broker SEBI registration Certificate", "remark": "yes"},
    {"sr_no": 9, "parameter": "Bank Statement for past 01 Year (For Bank Accounts mapped with MOFSL)", "remark": "yes"},
    {"sr_no": 10, "parameter": "Visitor Registers maintained at BA Office", "remark": "yes"},
    {"sr_no": 11, "parameter": "Compliant / Investor Grievance Register maintained at BA Office", "remark": "yes"},
    {"sr_no": 12, "parameter": "Inward / Outward Register maintained at BA Office", "remark": "yes"},
    {"sr_no": 13, "parameter": "Order instruction register or call recording samples (latest) whichever maintained at BA Office", "remark": "na"},
    {"sr_no": 14, "parameter": "Terminal ID no. verification photo", "remark": "yes"},
    {"sr_no": 15, "parameter": "No Unauthorised user operating terminals", "remark": "yes"},
    {"sr_no": 16, "parameter": "Approved/Unapproved User Photo ID proof (aadhar/pan/driving licence / voter id)", "remark": "yes"},
    {"sr_no": 17, "parameter": "Trade Detail obtained for the same day", "remark": "yes"},
    {"sr_no": 18, "parameter": "Client Detail Obtained incl. Client Code and Client Name", "remark": "yes"},
    {"sr_no": 19, "parameter": "Grivance Board", "remark": "no"},
    {"sr_no": 20, "parameter": "Auditor Selfie", "remark": "yes"},
    {"sr_no": 21, "parameter": "No Other broker terminal observed at AP location", "remark": "yes"},
    {"sr_no": 22, "parameter": "Call recordings and client order instructions are maintained and readily available.", "remark": "yes"},
    {"sr_no": 23, "parameter": "Authorized Person (AP) operates from the same address as registered with the exchange.", "remark": "yes"},
    {"sr_no": 24, "parameter": "Office has necessary infrastructure: adequate space, table, chairs, manpower, and operates from a clearly separated space (home/office/building).", "remark": "yes"},
    {"sr_no": 25, "parameter": "Proper data backup system is in place and regularly maintained.", "remark": "yes"},
    {"sr_no": 26, "parameter": "No illegal, dabba, or cash trading activities are conducted.", "remark": "yes"},
    {"sr_no": 27, "parameter": "AP does not maintain a trading account with any other broker.", "remark": "yes"},
    {"sr_no": 28, "parameter": "No unauthorized advertisements or promotional materials are circulated.", "remark": "yes"},
    {"sr_no": 29, "parameter": "No location change of AP/Branch has occurred", "remark": "yes"},
    {"sr_no": 30, "parameter": "If location change occurred, clients were notified at least 30 days in advance", "remark": "yes"},
    {"sr_no": 31, "parameter": "Social media accounts and bank statements reviewed; no guaranteed returns are promised to clients.", "remark": "yes"},
    {"sr_no": 32, "parameter": "All mandatory documents (contract notes, fund statements, daily margin statements) are generated and issued to clients by the AP.", "remark": "yes"},
    {"sr_no": 33, "parameter": "Any change in AP/Branch contact details (address, email, mobile) has been correctly reported and updated with the exchange.", "remark": "yes"},
    {"sr_no": 34, "parameter": "AP's mobile number and email ID are correctly mapped with their respective clients.", "remark": "yes"},
    {"sr_no": 35, "parameter": "AP's name does not imply advisory/investment services unless SEBI-registered; valid certificate available if applicable.", "remark": "yes"},
    {"sr_no": 36, "parameter": "No incentives are offered to clients for account opening.", "remark": "yes"},
    {"sr_no": 37, "parameter": "No movement of Funds between the clients.", "remark": "yes"},
    {"sr_no": 38, "parameter": "No fixed-amount payments are made at regular intervals without a legitimate reason.", "remark": "yes"},
    {"sr_no": 39, "parameter": "There are no repeated fund movements to/from the same counterparty, except where justified and documented.", "remark": "yes"},
    {"sr_no": 40, "parameter": "No high-value or frequent cash deposits are made in violation of regulatory norms.", "remark": "yes"},
    {"sr_no": 41, "parameter": "No other observations indicating potential non-compliance have been found.", "remark": "yes"},
    {"sr_no": 42, "parameter": "Any Other Observation write here", "remark": "no"}
]
